---
- name: create folders
  file: path={{ item }} state=directory
  with_items:
    - ~/bin
    - ~/laatu
- name: local bin
  file: path=~/bin/{{ item.name }} src={{ item.src }} state=link
  with_items:
   - { name: 'updatedb', src: '/usr/libexec/locate.updatedb' }
   - { name: 'vi', src: '/usr/local/bin/vim' }
- name: clone .dotfiles
  git: depth=1 dest=~/laatu/dot repo=https://github.com/wakeful/.dotfiles.git
       track_submodules=yes
- name: install .dotfiles
  shell: sudo cp -R -p {{ item }} ~/
  with_items:
    - ~/laatu/dot/*
    - ~/laatu/dot/.*
- name: install zsh plugins
  git: depth=1 dest=~/.oh-my-zsh-custom/plugins/{{ item.name }}
       repo={{ item.repo }}
  with_items:
    - { name: 'docker-machine',
        repo: 'https://github.com/wakeful/zsh-docker-machine.git' }
    - { name: 'packer',
        repo: 'https://github.com/wakeful/zsh-packer.git' }
- name: install vim plugins
  shell: vim +PluginInstall +qall
