---
- name: install packages
  become: yes
  pkgng: name={{ item }} state=present
  with_items:
    - xfce
    - xdm
    - xorg
- name: enable XDM
  become: yes
  lineinfile:
    dest: /etc/ttys
    regexp: '^ttyv8	"/usr/local/bin/xdm -nodaemon"'
    line: 'ttyv8	"/usr/local/bin/xdm -nodaemon"	xterm	on  secure'
- name: start dbus on system boot
  become: yes
  service: name=dbus enabled=yes
